name: Theme deploy
on:
  push:
    branches:
      - hunt-2
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - SHOPIFY_FLAG_STORE: 'meow-world-development'
            SHOPIFY_CLI_THEME_TOKEN: 'MWD_SHOPIFY_CLI_THEME_TOKEN'
            SHOPIFY_THEME_ID: '164839686455' # [UNSTABLE]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: ${{ matrix.SHOPIFY_FLAG_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets[matrix.SHOPIFY_CLI_THEME_TOKEN] }}
        run: shopify theme push --path ./ -t ${{ matrix.SHOPIFY_THEME_ID }}
