name: Theme deploy
on:
  push:
    branches:
      - hunt-2
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - SHOPIFY_FLAG_STORE: 'meow-world-development'
            SHOPIFY_CLI_THEME_TOKEN: 'MWD_SHOPIFY_CLI_THEME_TOKEN'
            SHOPIFY_THEME_ID: '164839686455' # [UNSTABLE]

          # - SHOPIFY_FLAG_STORE: 'dev-online-store-2'
          #   SHOPIFY_CLI_THEME_TOKEN: 'DEV_ONLINE_STORE_2_SHOPIFY_CLI_THEME_TOKEN'
          #   SHOPIFY_THEME_ID: '166294487354' # [UNSTABLE] Symmetry

          # - SHOPIFY_FLAG_STORE: 'huntbikewheels'
          #   SHOPIFY_CLI_THEME_TOKEN: 'HUNT_UK_SHOPIFY_CLI_THEME_TOKEN'
          #   SHOPIFY_THEME_ID: '126300192845' # [UNSTABLE] Symmetry

          # - SHOPIFY_FLAG_STORE: 'huntbikewheels-us'
          #   SHOPIFY_CLI_THEME_TOKEN: 'HUNT_US_SHOPIFY_CLI_THEME_TOKEN'
          #   SHOPIFY_THEME_ID: NOT_YET_CREATED

          # - SHOPIFY_FLAG_STORE: 'huntbikewheels-eu'
          #   SHOPIFY_CLI_THEME_TOKEN: 'HUNT_EU_SHOPIFY_CLI_THEME_TOKEN'
          #   SHOPIFY_THEME_ID: '131981934784' # [UNSTABLE] Symmetry

          # - SHOPIFY_FLAG_STORE: 'huntbikewheels-cc'
          #   SHOPIFY_CLI_THEME_TOKEN: 'HUNT_CC_SHOPIFY_CLI_THEME_TOKEN'
          #   SHOPIFY_THEME_ID: NOT_YET_CREATED

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: ${{ matrix.SHOPIFY_FLAG_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets[matrix.SHOPIFY_CLI_THEME_TOKEN] }}
        run: shopify theme push --path ./ -t ${{ matrix.SHOPIFY_THEME_ID }}
