name: Lint and Pre-commit

on: [push, pull_request]

jobs:
  lint_and_pre_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - run: pip install pre-commit

    - run: pre-commit run --all-files

    - run: npm init

    - run: npm run lint
