name: Lint and Pre-commit

on: [push, pull_request]

jobs:
  lint_and_pre_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - uses: actions/setup-node@v4

    - run: pip install pre-commit

    - run: pre-commit run --all-files

    - run: npm install -g semistandard

    - run: npx semistandard --fix
